### ISSUE TITLE
Can't training with GPU

### ISSUE THREAD

**Issue by lovekittynine** [KaiyangZhou/deep-person-reid#259]
In the version of pytorch 1.3.1, OsNet can't train with GPU, report CUDA out of memory, but the gpu  is not occupied。Bug？

**Comment by lovekittynine** [comment]
even set bs=1, also report CUDA out of memor

**Comment by KaiyangZhou** [comment]
what's the full command line to reproduce ur error?

pls provide more info such as system ...

**Comment by ljx6666** [comment]
I have the same problem, my computer system is linux, and the processor is AMD FX(tm)-8150 Eight-Core Processor *8，please help me! Thank you !

**Comment by KaiyangZhou** [comment]
@lovekittynine did you find what's going on?

**Comment by ljx6666** [comment]
My video card is GTX1080ti with 11G . I only have this one.  Is there not enough video memory?

**Comment by KaiyangZhou** [comment]
@ljx6666 are you using scripts/main.py to run the code? if so, what's the full command you used?

**Comment by lovekittynine** [comment]
@KaiyangZhou @ljx6666  maybe you can try train with script: CUDA_VISIBLE_DEVICES=0 python3 train.py，explictly set GPU

**Comment by ljx6666** [comment]
Thank you for your patience!&nbsp;&nbsp;I have solved the problem.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lovekittynine"<notifications@github.com&gt;; 
发送时间: 2019年12月11日(星期三) 下午4:02
收件人: "KaiyangZhou/deep-person-reid"<deep-person-reid@noreply.github.com&gt;; 
抄送: "白开水"<916679590@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [KaiyangZhou/deep-person-reid] Can&#39;t training with GPU (#259)




@KaiyangZhou @ljx6666  maybe you can try train with script: CUDA_VISIBLE_DEVICES=0 python3 train.py，explictly set GPU

**Comment by KaiyangZhou** [comment]
please note that in the latest commit, you need to explicitly set `CUDA_VISIBLE_DEVICES `
