### ISSUE TITLE
PyTorch is not using the GPU specified by gpu_devices

### ISSUE THREAD

**Issue by justopit** [KaiyangZhou/deep-person-reid#267]
When I set gpu_devices = 0, it will run all gpus in the server. And I tried to put "CUDA_VISIBLE_DEVICES=0" before "python scripts/main.py",  the same thing occurred.

**Comment by KaiyangZhou** [comment]
`CUDA_VISIBLE_DEVICES` is supposed to globally set the gpu device so I am not sure why. Are you using the latest commit?

Could you help me check what's going on in this [line](https://github.com/KaiyangZhou/deep-person-reid/blob/master/scripts/main.py#L140) when you run the program? I only have one gpu so I am unable to check this error

**Comment by justopit** [comment]
It is true and 'os.environ['CUDA_VISIBLE_DEVICES'] = args.gpu_devices' work. But torch.cuda.device_count() shows 4（the number of GPUS in my server）. With the help of my schoolmate, I found a solution. Just in the beginning of main.py, insert *os.environ['CUDA_VISIBLE_DEVICES'] = args.gpu_devices*.  And the reason is https://github.com/pytorch/pytorch/issues/9158?!

**Comment by KaiyangZhou** [comment]
The reason I put `CUDA_VISIBLE_DEVICES` inside the main function is because I want this option to be disabled when one doesn't want to specify the gpu. This is useful in the case where the gpu server assigns a gpu to you (e.g., condor system) instead of allowing you to choose.

Maybe it's better to remove this option and let users manually add this global variable before `python main.py` if they want. What do you think?

**Comment by justopit** [comment]
I have little knowledge about condor system. But the code(based on you) below may help
![BCB7C7DE-1A42-46EE-9A83-9485B0EF4A10](https://user-images.githubusercontent.com/24216298/69963126-8157ce80-154a-11ea-8045-5747401ee6d4.png)

**Comment by justopit** [comment]
> I have little knowledge about condor system. But the code(based on you) below may help
> ![BCB7C7DE-1A42-46EE-9A83-9485B0EF4A10](https://user-images.githubusercontent.com/24216298/69963126-8157ce80-154a-11ea-8045-5747401ee6d4.png)

the code would work well. By the way, put CUDA_VISIBLE_DEVICES inside *'if __name__ == '__main__':'* does not work(In my another program, it work). I don't know why.

**Comment by KaiyangZhou** [comment]
So it looks like it doesn't have to put the variable before `import torch`?

I just pushed a commit based on your code. Please have a check and let me know if it works

**Comment by justopit** [comment]
Sorry to be so late to give your answer. It does not work.

**Comment by KaiyangZhou** [comment]
ok thanks

I will remove the variable
